### ISSUE TITLE
ALWAYS pass "bot" to functions

### ISSUE THREAD

**Issue by deathbybandaid** [deathbybandaid/SpiceBot#1174]
let's get in the habit of passing bot to functions,, it makes it a great deal easier to test code, when you can use "bot.say"

**Comment by josh-cunning** [comment]
Easier for testing but it gets harder to work with if a lot of shared functions all have bot.say commands.

**Comment by josh-cunning** [comment]
We could start using some optional arguments so we don't have to rewrite functions like all the get_triggerarg ones: 

https://docs.python.org/2/tutorial/controlflow.html#default-argument-values

just add a default value for bot and if it is default skip say command

get_trigger_arg(x,1)
get_trigger_arg(bot,x,1)

def get_trigger_arg(bot='none', inputs, outputtask):
if not bot = 'none' 
bot.say ( "error testing")

**Comment by Berserkir-Wolf** [comment]
I've been passing bot to functions so the function can figure out bot.nick etc for target evaluations.
Shared functions should return a string/bool. They should only speak in the case of being a check to allow/not allow further code. Have them say "no" and the other code stop, rather than building handlers in multiple places.

**Comment by deathbybandaid** [comment]
just seems easiest to put pass bot

**Comment by josh-cunning** [comment]
You both made a lot of sense and I agree with you. One reasons I suggest the optional function was so we could use the new trigger args without have to rewrite every module. 
It would be good to go through them again and fix other things so I am all for it. 

We should consider eliminating some of modules that never get used at the same time. Using the nukeit example we could just combine a lot of them and save a bit of updating code in the future.

**Comment by Berserkir-Wolf** [comment]
Nuke was mostly done that way as a way to get my head around certain function types and which arg was which. It needs to be split out again.
Given that we're trying to get rid of modules with multiple separate things in them, I'd say no to combining them again.
Modules like "yes" have multiple variations on the same command, and subcommands are fine as well.
Multiple separate commands are something we're trying to eliminate, so that errors in code only affect one thing at a time instead of multiple things. That way we can take a single module offline to develop further instead of a bunch together. Weather was a good example - making setlocation a subcommand rather than a whole other commandword.
